---
title: Hands-on Computer Vision
sidebar: false
format:
  html:
    toc: false
    page-layout: full




---

<header>
    <h2>De los Conceptos al Código</h2>
</header>

<main>
<section class="introduction">
    <h3>Introducción al Semillero</h3>
    <p>
        Sumérgete en una experiencia práctica y teórica con nuestro semillero "Hands-on Computer Vision". Aprende y aplica conocimientos en visión por computadora para resolver problemas reales, utilizando tecnologías de punta como OpenCV y Python.
    </p>
</section>

<section class="upcoming-sessions">
    <h3>Cronograma</h3>
    <table style="width: 100%; border-collapse: collapse; margin-top: 20px;">
        <thead>
            <tr style="background-color: #f2f2f2;">
                <th style="padding: 12px 15px; border: 1px solid #ddd;">Fecha</th>
                <th style="padding: 12px 15px; border: 1px solid #ddd;">Título</th>
                <th style="padding: 12px 15px; border: 1px solid #ddd;">Descripción</th>
            </tr>
        </thead>
        <tbody>
            <tr style="transition: background-color 0.3s ease;">
                <td style="padding: 10px 15px; border: 1px solid #ddd;">Sesión 1</td>
                <td style="padding: 10px 15px; border: 1px solid #ddd;">1 piloto</td>
                <td style="padding: 10px 15px; border: 1px solid #ddd;">todos</td>
            </tr>
            <tr style="transition: background-color 0.3s ease;">
                <td style="padding: 10px 15px; border: 1px solid #ddd;">Sesión 2</td>
                <td style="padding: 10px 15px; border: 1px solid #ddd;">2 generalidades imágenes</td>
                <td style="padding: 10px 15px; border: 1px solid #ddd;"><span style="color: red;">Hoover</span></td>
            </tr>
            <tr style="transition: background-color 0.3s ease;">
                <td style="padding: 10px 15px; border: 1px solid #ddd;">Sesión 3</td>
                <td style="padding: 10px 15px; border: 1px solid #ddd;">3 espectral</td>
                <td style="padding: 10px 15px; border: 1px solid #ddd;"><span style="color: red;">Cristian y Miguel</span></td>
            </tr>
            <tr style="transition: background-color 0.3s ease;">
                <td style="padding: 10px 15px; border: 1px solid #ddd;">Sesión 4</td>
                <td style="padding: 10px 15px; border: 1px solid #ddd;">4 depth pasivo</td>
                <td style="padding: 10px 15px; border: 1px solid #ddd;"><span style="color: red;">Ramiro y Miguel</span></td>
            </tr>
            <tr style="transition: background-color 0.3s ease;">
                <td style="padding: 10px 15px; border: 1px solid #ddd;">Sesión 5</td>
                <td style="padding: 10px 15px; border: 1px solid #ddd;">5 depth activo</td>
                <td style="padding: 10px 15px; border: 1px solid #ddd;"><span style="color: red;">Ramiro y Hoover</span></td>
            </tr>
            <tr style="transition: background-color 0.3s ease;">
                <td style="padding: 10px 15px; border: 1px solid #ddd;">Sesión 6</td>
                <td style="padding: 10px 15px; border: 1px solid #ddd;">6 deep learning crash => projects definition</td>
                <td style="padding: 10px 15px; border: 1px solid #ddd;"><span style="color: red;">Fabian y Hoover</span></td>
            </tr>
            <tr style="transition: background-color 0.3s ease;">
                <td style="padding: 10px 15px; border: 1px solid #ddd;">Sesión 7</td>
                <td style="padding: 10px 15px; border: 1px solid #ddd;">7 segmentación</td>
                <td style="padding: 10px 15px; border: 1px solid #ddd;"><span style="color: red;">Fabian y Cristian</span></td>
            </tr>
            <tr style="transition: background-color 0.3s ease;">
                <td style="padding: 10px 15px; border: 1px solid #ddd;">Sesión 8</td>
                <td style="padding: 10px 15px; border: 1px solid #ddd;">8 thermal imaging</td>
                <td style="padding: 10px 15px; border: 1px solid #ddd;"><span style="color: red;">Oscar y Hoover</span></td>
            </tr>
            <tr style="transition: background-color 0.3s ease;">
                <td style="padding: 10px 15px; border: 1px solid #ddd;">Sesión 9</td>
                <td style="padding: 10px 15px; border: 1px solid #ddd;">9 tinyml</td>
                <td style="padding: 10px 15px; border: 1px solid #ddd;"><span style="color: red;">Fabian y Oscar</span></td>
            </tr>
            <tr style="transition: background-color 0.3s ease;">
                <td style="padding: 10px 15px; border: 1px solid #ddd;">Sesión 10</td>
                <td style="padding: 10px 15px; border: 1px solid #ddd;">10 projects</td>
                <td style="padding: 10px 15px; border: 1px solid #ddd;"></td>
            </tr>
        </tbody>
    </table>
</section>



<section class="join">
    <h3>Participa en el Semillero</h3>
    <p>
        ¿Listo para unirte? Inscríbete y comienza a explorar el apasionante campo de la visión por computadora con nosotros.
    </p>
    <a class="button" href="inscripcion.qmd">Inscribirse Ahora</a>
</section>
</main>

<footer>
    <p>Para consultas, contacta a <a href="mailto:contacto@handson-cv.edu">contacto@handson-cv.edu</a>.</p>
</footer>